CC = gcc

single: single.o shuffle.o beggar.o
	gcc -o single single.o shuffle.o beggar.o -lgsl -lgslcblas -lm

byn: byn.o shuffle.o beggar.o
	gcc -o byn byn.o shuffle.o beggar.o -lgsl -lgslcblas -lm

